apiVersion: v1
kind: Secret
metadata:
  name: wallet-tracking-service-secrets
  namespace: supai
type: Opaque
stringData:
  DATABASE_URL: "postgresql://neondb_owner:npg_CimHrb16YtyD@ep-muddy-night-agidrotj-pooler.c-2.eu-central-1.aws.neon.tech/wallet-tracking?sslmode=require&channel_binding=require"
  ALCHEMY_AUTH_TOKEN: "MeUyrthPQP8PI6SHT4lwtp_OHpbqbhFy"
  ALCHEMY_APP_ID: "w19n9qvx2pr6u01x"
  ALCHEMY_WEBHOOK_ID: "wh_yxg2izkjty3odk2g"
  ALCHEMY_WEBHOOK_SIGNING_KEY: "whsec_tE9CcC7raEk4tnmE4TtzMPEB"
  INTERNAL_SERVICE_KEY: "supai-internal-key-2026"
