apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-config
  namespace: supai
data:
  PORT: "3001"
  NODE_ENV: "production"
  BETTER_AUTH_URL: "http://localhost/api/auth"
  TRUSTED_ORIGINS: "http://localhost:3000,http://localhost:3006"
  RABBITMQ_URL: "amqp://rabbitmq_admin:rabbitmqpassword@rabbitmq:5672"
