apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-service-config
  namespace: supai
data:
  PORT: "3005"
  NODE_ENV: "production"
  RABBITMQ_URL: "amqp://rabbitmq_admin:rabbitmqpassword@rabbitmq:5672"
  USER_SERVICE_URL: "http://user-service:3007"
