apiVersion: v1
kind: Secret
metadata:
  name: notification-service-secrets
  namespace: supai
type: Opaque
stringData:
  DATABASE_URL: "postgresql://neondb_owner:npg_CimHrb16YtyD@ep-muddy-night-agidrotj-pooler.c-2.eu-central-1.aws.neon.tech/notification?sslmode=require&channel_binding=require"
  TELEGRAM_BOT_TOKEN: "8253112005:AAGEDDoiG9zw9A3lA-JM7YnYSAZkV_pQ5-A"
  INTERNAL_SERVICE_KEY: "supai-internal-key-2026"
