apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
  namespace: supai
data:
  PORT: "3007"
  NODE_ENV: "production"
  RABBITMQ_URL: "amqp://rabbitmq_admin:rabbitmqpassword@rabbitmq:5672"
