apiVersion: v1
kind: Secret
metadata:
  name: user-service-secrets
  namespace: supai
type: Opaque
stringData:
  DATABASE_URL: "postgresql://neondb_owner:npg_CimHrb16YtyD@ep-muddy-night-agidrotj-pooler.c-2.eu-central-1.aws.neon.tech/user?sslmode=require&channel_binding=require"
  INTERNAL_SERVICE_KEY: "internal-service-key-here"
